# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('website_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Website URL')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('products_description', models.TextField(blank=True, verbose_name='Producs Descripition')),
                ('extra_description', models.TextField(blank=True, verbose_name='Others Products Infromation')),
                ('social_facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Facebook')),
                ('social_instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Instagram')),
                ('social_other', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Social Other')),
                ('business_description', models.TextField(blank=True, verbose_name='Business Description')),
                ('certifications', models.TextField(blank=True, verbose_name='Certifications')),
            ],
            options={
                'ordering': ('-id',),
                'db_table': 'core_joinrequest',
                'verbose_name': 'Join Request',
                'verbose_name_plural': 'Join Requests',
            },
        ),
        migrations.CreateModel(
            name='SignUpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'ordering': ('-id',),
                'db_table': 'core_signuprequest',
                'verbose_name': 'Sign Up Request',
                'verbose_name_plural': 'Sign Up Requests',
            },
        ),
    ]
