# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160719_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productunit',
            old_name='unit_attributes',
            new_name='attributes',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.Product', verbose_name='Product'),
        ),
    ]
