# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160720_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSampleDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qunatity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('trackign_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tracking Number')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('SHP', 'Shipped'), ('DLV', 'Delivered')], default='PEN', max_length=50, verbose_name='Status')),
                ('shipping_company', models.CharField(blank=True, max_length=255, null=True)),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProductUnit', verbose_name='Product Unit')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Store')),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='store',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'USD', 'US Dollar'), (b'UYU', 'Uruguayan peso')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='productsampledispatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Warehouse', verbose_name='Warehouse'),
        ),
    ]
