# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160722_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsampledispatch',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
