# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160722_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
