# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='object_id',
            field=models.CharField(default=1, max_length=200, verbose_name='Object id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='object_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Objcet Type'),
            preserve_default=False,
        ),
    ]
