# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 13:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160726_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncompleteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('currency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Currency')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Attributes')),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Validation Errors')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Store')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
