# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160728_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='incompleteproduct',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date added'),
        ),
        migrations.AddField(
            model_name='incompleteproduct',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File Name'),
        ),
    ]
