# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160728_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incompleteproduct',
            old_name='price',
            new_name='price_amount',
        ),
        migrations.RenameField(
            model_name='incompleteproduct',
            old_name='currency',
            new_name='price_currency',
        ),
        migrations.RenameField(
            model_name='incompleteproduct',
            old_name='attributes',
            new_name='units',
        ),
        migrations.RemoveField(
            model_name='incompleteproduct',
            name='file_name',
        ),
    ]
