# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160728_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Products Quantity'),
            preserve_default=False,
        ),
    ]
