# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incompleteproduct',
            name='sku',
        ),
        migrations.AddField(
            model_name='productunit',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU'),
        ),
    ]
