# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnitSampleDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
            ],
        ),
        migrations.RemoveField(
            model_name='productsampledispatch',
            name='product_unit',
        ),
        migrations.RemoveField(
            model_name='productsampledispatch',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productsampledispatch',
            name='showroom',
            field=models.ManyToManyField(to='core.Showroom', verbose_name='Showrooms'),
        ),
        migrations.AddField(
            model_name='productunitsampledispatch',
            name='product_sample_dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples_units',
                                    to='core.ProductSampleDispatch', verbose_name='Sample Dispatch'),
        ),
        migrations.AddField(
            model_name='productunitsampledispatch',
            name='product_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProductUnit', verbose_name='Product Unit'),
        ),
    ]
