# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160803_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSampleUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProductUnit', verbose_name='Product Unit')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductSampleDispatch',
            new_name='SampleDispatch',
        ),
        migrations.RemoveField(
            model_name='productunitsampledispatch',
            name='product_sample_dispatch',
        ),
        migrations.RemoveField(
            model_name='productunitsampledispatch',
            name='product_unit',
        ),
        migrations.DeleteModel(
            name='ProductUnitSampleDispatch',
        ),
        migrations.AddField(
            model_name='productsampleunits',
            name='sample_dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples_units', to='core.SampleDispatch', verbose_name='Sample Dispatch'),
        ),
    ]
