# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160803_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampledispatch',
            old_name='trackign_number',
            new_name='tracking_number',
        ),
        migrations.AlterField(
            model_name='sampledispatch',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('PRG', 'In Progress'), ('SHP', 'Shipped'), ('DLV', 'Delivered'), ('RET', 'Returned')], default='PEN', max_length=50, verbose_name='Status'),
        ),
    ]
