# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20160804_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Store')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('attribute_name', models.CharField(max_length=255, verbose_name='Cached attribute name')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Attribute', verbose_name='Attribute')),
            ],
            options={
                'ordering': ('value',),
            },
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='attributes',
        ),
        migrations.AlterField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.Category', verbose_name='Parent Category'),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(to='core.Attribute', verbose_name='Product Attributes'),
        ),
    ]
