# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_productunit_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='ordering',
            field=models.IntegerField(default=0, help_text='Ascendent', verbose_name='Ordering'),
        ),
    ]
