# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20160808_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incompleteproduct',
            name='category',
            field=models.IntegerField(blank=True, null=True, verbose_name='Category'),
        ),
    ]
