# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20160808_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='core.Category', verbose_name='Categories'),
        ),
    ]
