# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_attribute_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductUnitLocation',
            new_name='Sample',
        ),
        migrations.AlterModelOptions(
            name='sampledispatch',
            options={'verbose_name': 'Dispatched Sample', 'verbose_name_plural': 'Dispatched Samples'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='If a category is selected then subcategories are included too', related_name='attributes', to='core.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='store',
            field=models.ForeignKey(blank=True, help_text='If this attribute is only usable for a store', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Store'),
        ),
    ]
