# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20160811_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number'),
        ),
    ]
