# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_consumer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewType',
            fields=[
                ('name', models.SlugField(max_length=255, primary_key=True, serialize=False, verbose_name='Analyics Nmae')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Date From')),
                ('date_to', models.DateField(verbose_name='Date To')),
                ('value', models.BigIntegerField(verbose_name='Value')),
                ('aggregate_value', models.BigIntegerField(verbose_name='Aggregate Value')),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(related_name='stores', to='core.Category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='periodoverview',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='periodoverview',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OverviewType', verbose_name='Overview Type'),
        ),
    ]
