# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20160822_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'ordering': ('city__country__name', 'name'),
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_stores', to='core.Region', verbose_name='Region')),
            ],
            options={
                'ordering': ('region',),
                'verbose_name': 'Store Location',
                'verbose_name_plural': 'Store Locations',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('country__name', 'name'), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='overviewtype',
            options={'verbose_name': 'Overview Type', 'verbose_name_plural': 'Overview Types'},
        ),
        migrations.AlterModelOptions(
            name='periodoverview',
            options={'verbose_name': 'Period Overview', 'verbose_name_plural': 'Period Overviews'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='store',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='periodoverview',
            name='aggregate_value',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Aggregate Value'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_location', to='core.Store', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='region',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='City'),
        ),
    ]
