# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20160901_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Image', verbose_name='Image'),
        ),
    ]
