# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20160905_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='object_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Object id'),
        ),
        migrations.AlterField(
            model_name='image',
            name='object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Objcet Type'),
        ),
    ]
