# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20160906_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Landscape URL'),
        ), migrations.AlterField(
            model_name='image',
            name='medium_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Portrait URL'),
        ), migrations.AlterField(
            model_name='image',
            name='small_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Small URL'),
        ), migrations.AlterField(
            model_name='image',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ), migrations.RenameField(
            model_name='image',
            old_name='thumbnail_url',
            new_name='url',
        ), migrations.RenameField(
            model_name='image',
            old_name='medium_url',
            new_name='portrait_url',
        ), migrations.RenameField(
            model_name='image',
            old_name='large_url',
            new_name='landscape_url',
        ),
    ]
