# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_incompleteproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='countries',
            field=models.ManyToManyField(related_name='country_store', to='core.Country', verbose_name='Countries'),
        ),
    ]
