# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_store_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='store',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Do not alter this directly, add or delete regions instead.', related_name='country_store', to='core.Country', verbose_name='Countries'),
        ),
    ]
