# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 13:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20160913_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Links to videos'),
        ),
    ]
