# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 14:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_store_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Only boolean attribtues should have images', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Image', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_boolean',
            field=models.BooleanField(default=False, verbose_name='If this attribute has no values'),
        ),
        migrations.AlterField(
            model_name='store',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='To add more than one separate them with ,', null=True, size=None, verbose_name='Links to videos'),
        ),
    ]
