# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_country_in_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
    ]
