# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_order_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledispatch',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created'),
        ),
    ]
