# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_sampledispatch_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampledispatch',
            options={'ordering': ('-created', '-id'), 'verbose_name': 'Dispatched Sample', 'verbose_name_plural': 'Dispatched Samples'},
        ),
        migrations.AddField(
            model_name='product',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount sold'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'EUR', 'Euro'), (b'USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
