# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20160926_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_unit_id',
            new_name='product_unit',
        ),
    ]
