# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0051_auto_20160926_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Object id'),
        ),
        migrations.AddField(
            model_name='sample',
            name='object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Objcet Type'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SampleDispatch', verbose_name='Sample Dispatch'),
        ),
        migrations.AddField(
            model_name='sample',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='sampledispatch',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Received By'),
        ),
    ]
