# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20160928_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='name_zh_hans',
            new_name='name_zh_tw',
        ),
        migrations.RenameField(
            model_name='attributevalue',
            old_name='value_zh_hans',
            new_name='value_zh_tw',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_zh_hans',
            new_name='name_zh_tw',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name_zh_hans',
            new_name='name_zh_tw',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='description_zh_hans',
            new_name='description_zh_tw',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name_zh_hans',
            new_name='name_zh_tw',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_zh_hans',
            new_name='description_zh_tw',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_zh_hans',
            new_name='name_zh_tw',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='description_zh_hans',
            new_name='description_zh_tw',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name_zh_hans',
            new_name='name_zh_tw',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='description_zh_hans',
            new_name='description_zh_tw',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='name_zh_hans',
            new_name='name_zh_tw',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='name_zh_hans',
            new_name='name_zh_tw',
        ),
        migrations.AlterField(
            model_name='sample',
            name='showrooms',
            field=models.ManyToManyField(blank=True, to='core.Showroom', verbose_name='Showrooms'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showrooms', to='core.Warehouse', verbose_name='Warehouse'),
        ),
    ]
