# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20160928_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='name_zh_tw',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='attributevalue',
            old_name='value_zh_tw',
            new_name='value_zh_hans',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_zh_tw',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name_zh_tw',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='description_zh_tw',
            new_name='description_zh_hans',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name_zh_tw',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_zh_tw',
            new_name='description_zh_hans',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_zh_tw',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='description_zh_tw',
            new_name='description_zh_hans',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name_zh_tw',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='description_zh_tw',
            new_name='description_zh_hans',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='name_zh_tw',
            new_name='name_zh_hans',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='name_zh_tw',
            new_name='name_zh_hans',
        ),
    ]
