# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20160929_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular_in',
            field=models.ManyToManyField(blank=True, related_name='popular_products', to='core.Country', verbose_name='Popular In'),
        ),
        migrations.AddField(
            model_name='store',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Popularity'),
        ),
    ]
