# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20161005_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is this product approved'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='core.Attribute', verbose_name='Product Attributes'),
        ),
    ]
