# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_unapprovedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='infographics',
            field=models.ManyToManyField(blank=True, to='core.Image', verbose_name='Infographics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='core.Image', verbose_name='Main image'),
        ),
        migrations.AlterField(
            model_name='store',
            name='popularity',
            field=models.IntegerField(default=0, help_text='More is better', verbose_name='Popularity'),
        ),
    ]
