# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20161017_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_approved',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Approved'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
