# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number'),
        ),
    ]
