# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20161104_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinrequest',
            options={'ordering': ('-id',), 'verbose_name': 'Join Request', 'verbose_name_plural': 'Join Requests'},
        ),
    ]
