# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_signuprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinRequest',
        ),
        migrations.DeleteModel(
            name='SignUpRequest',
        ),
        migrations.AddField(
            model_name='store',
            name='extra_information',
            field=models.TextField(blank=True, null=True, verbose_name='Extra information'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[(b'CNY', 'Yuan Renminbi')], default='USD', editable=False, max_length=3),
        ),
    ]
