# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20161121_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='extra_information_en',
            field=models.TextField(blank=True, null=True, verbose_name='Extra information'),
        ),
        migrations.AddField(
            model_name='store',
            name='extra_information_es',
            field=models.TextField(blank=True, null=True, verbose_name='Extra information'),
        ),
        migrations.AddField(
            model_name='store',
            name='extra_information_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Extra information'),
        ),
    ]
