# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20161121_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='object_id2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Object id 2'),
        ),
    ]
